import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import { ThemeContextProvider } from "@/context/ThemeContext";


const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "News portal",
  description: "Generated by nextjs",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={roboto.className}
      >
        <ThemeContextProvider>
          <Navbar></Navbar>
          <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 min-h-screen">
            {children}
          </main>
          <footer>
            <Footer></Footer>
          </footer>
        </ThemeContextProvider>

      </body>
    </html>
  );
}
